config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  resources :chapters, :materials, only: [:index, :show]
  match '/meetups/:slug' => 'meetups#show', via: :get

  get '/materials/:slug' => 'materials#show', as: :course

  get 'about', to: 'home#about'
  get 'code-of-conduct', to: 'home#code-of-conduct'
  get 'codeofconduct', to: redirect('code-of-conduct')
  get 'materials', to: 'materials#index'
  get 'curriculum', to: redirect('materials')
  get 'sponsors', to: 'home#sponsors'
  get 'donate', to:'home#donate'
  get "*any", via: :all, to: "errors#404"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    allroles = []
    user.roles.each do |r|
      allroles << r.name
    end
    if allroles.include? "admin"
      can :manage, :all
    elsif allroles.include? "leader"
      #allow view of Dashboard page
      can :read, ActiveAdmin::Page, name: 'Dashboard'

      #leader can only view/update chapter details (not create)
      can [:read, :view, :manage], Chapter, :id => user.chapter_id
     
      #only list/manage the bios and sponsors related leader's chapter
      can [:manage, :read, :view], [Bio, Sponsor], :chapter_id => user.chapter_id

      #leader can create new bios and sponsors, but chapter_id is hidden in form
      can :create, [Bio, Sponsor]

      #leaders cannot create new chapters
      cannot :create, Chapter

      #leaders cannot view adminuser page
      cannot :read, AdminUser
    else
      can :view, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :bio
  belongs_to :chapter
  accepts_nested_attributes_for :roles
end

app/models/bio.rb
class Bio < ActiveRecord::Base
  resourcify
  belongs_to :admin_user
  belongs_to :chapter

  mount_uploader :image, ProfileImageUploader
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  extend FriendlyId
  friendly_id :chapter, use: [:slugged, :history]

  resourcify
  has_many :admin_users
  has_many :sponsors
  has_many :bios

  geocoded_by :geo
  after_validation :geocode
  after_validation :geocode, :if => :geo_changed?

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geocoded = results.first
      obj.state = geocoded.state
    end
  end
  after_validation :reverse_geocode
end

app/models/material.rb
class Material < ActiveRecord::Base
  resourcify
  mount_uploader :icon, MaterialIconUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  resourcify
  has_and_belongs_to_many :admin_users, :join_table => :admin_users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  resourcify
  belongs_to :chapter
  mount_uploader :image, SponsorImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def access_denied(exception)
    redirect_to root_path, :alert => exception.message
  end


  # private
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   # binding.pry
  #   root_path
  # end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  require 'rails_autolink'
  def index
    @chapters = Chapter.order("chapter ASC").all
    states = {}
    @chapters.each do |l|
      if states[l.state]
        states[l.state] << l.chapter
      else
        states[l.state] = [l.chapter]
      end
    end
    @states = states.to_a.sort

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @chapters }
  end
end

  def show
    @chapter = Chapter.friendly.find(params[:id])
    if request.path != chapter_path(@chapter)
      redirect_to @chapter, status: :moved_permanently
    end
    @users = @chapter.admin_users
    @sponsors = @chapter.sponsors

    @bios = @chapter.bios
    @leaders = @bios.where(title: "LEADERS")
    @instructors = @bios.where(title: "INSTRUCTORS")
    @volunteers = @bios.where(title: "VOLUNTEERS")

    api = MeetupApi.new
    @events = api.events(group_id: @chapter.meetup_id)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  @chapters = Chapter.all
  @chapter = Chapter.all
  end

  def about
  end

  def donate
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  require 'rails_autolink'
  def index
    @materials = Material.all

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @materials }
  end
end

  def show
   @material = Material.find_by(slug: params[:id])
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController

  def show
    ## Someday there will be caching here!
    @chapter = Chapter.find_by(slug: params[:slug])

    params = { group_id: @chapter.meetup_id, key: ENV["MEETUP_API_KEY"]}
    meetup_api = MeetupApi.new
    @glob = meetup_api.events(params)
    @results = @glob["results"]

    respond_to do |format|
      format.json { render json: @results }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_page(path)
    "active-nav" if current_page?(path)
  end

  def full_title(page_title = '')
    base_title = "Girl Develop It"
    if page_title.empty?
      base_title
    else
      "#{page_title}  -  #{base_title}"
    end
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
  def image_route(s)
    "state_map/#{s.parameterize}.png"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/chapters/_meetup_map.html.erb
 <p class="meetup-map hide">
  <%% if( typeof course.venue !== "undefined" && course.visibility === "public" && course.venue.lat !== 0) { %>
    <img src= "https://maps.google.com/maps/api/staticmap?size=800x450&sensor=false&zoom=16&markers=<%%= course.venue.lat %>%2C<%%= course.venue.lon %>" alt="chapter map">
  <%% } %>
</p>

app/views/chapters/_social_media_bio.html.erb
<ul class="media-links">
  <% if bio.email? %>
    <%= mail_to bio.email do %>
      <i class="fa fa-envelope"></i>
    <% end %>
  <% end %>

  <% if bio.website? %>
    <%= link_to bio.website do %>
      <i class="fa fa-globe"></i>
    <% end %>
  <% end %>

  <% if bio.twitter? %>
    <%= link_to "https://twitter.com/#{bio.twitter}" do %>
      <i class="fa fa-twitter"></i>
    <% end %>
  <% end %>

  <% if bio.linkedin? %>
    <%= link_to "https://www.linkedin.com/in/#{bio.linkedin}" do %>
      <i class="fa fa-linkedin"></i>
    <% end %>
  <% end %>

  <% if bio.github? %>
    <%= link_to "https://www.github.com/#{bio.github}" do %>
      <i class="fa fa-github-alt"></i>
    <% end %>
  <% end %>
</ul>

app/views/chapters/index.html.erb
<% provide(:title, "Chapters") %>
  <section class="main-container">
  <div class="container">

    <div class="underlined-headline">
      <h2>We are now in <%= @chapters.count %> cities!</h2>
        <hr><p class="subtitle hide">Don't see your hometown?
          <% if current_admin_user != nil %>
            <%= link_to "Start a new chapter!", "#{root_path}admin/chapters/new" %></p>
            <% else %>
            <a href="https://docs.google.com/a/girldevelopit.com/forms/d/1IwGncJ6_69MWa2_rrikO5Q3DLriA04Eq9x0BUnxkwTw/viewform?edit_requested=true#start=invite">Start a new chapter!</a></p>
          <% end %>
        </p>
    </div>

    <section class="state-index hide">
      <% @states.each do |s| %>
        <div class="state-container">
          <div class="state"><%= image_tag(image_route(s[0])) %></div>
          <hr>
          <h2><%= s[0] %></h2>
          <% s[1].each do |l| %>
            <h3 class="large"><%= link_to l, chapter_path(l.parameterize) %></h3>
          <% end %>
        </div>
    <% end %>
    </section>

    <section id="state-list">
      <div class="accordion show">
        <% @states.each do |s| %>
          <section class="hidden">
            <h2><%= s[0] %></h2>
            <ul>
              <% s[1].each do |l| %>
                <li><h3><%= link_to l, chapter_path(l.parameterize) %><h3></li>
              <% end %>
            </ul>
          </section>
        <% end %>
      </div>
    </section>
  </div>
  </section>

app/views/chapters/show.html.erb
<% provide(:title, "#{@chapter.chapter}") %>
<section class="main-container">
  <div class="container">
    <aside class="chapter-aside">
      <div class="state-container-aside">
        <%= link_to image_tag(image_route(@chapter.state)), chapters_path %>
      </div>
      <hr>
      <h1><%= @chapter.chapter %></h1>

      <%= render partial: "social_media_chapter", locals: {user: @chapter} %>

      <p class="subtitle">- don't be shy -</p>
      <%= link_to "{ Join Us }", "http://www.meetup.com/#{@chapter.meetup}", :class=>"button" %>

      <% if @chapter.sponsors.count != 0 %>
        <div class="hide">
          <div class="sponsors">
            <h2>Sponsors</h2>
            <div class="logos">
              <% @sponsors.each do |sponsor| %>
                <% if sponsor.image? %>
                  <%= link_to image_tag(sponsor.image.url), sponsor.url, target: "_blank" %>
                <% elsif sponsor.name? %>
                  <%= link_to sponsor.url, target: "_blank", :class=>"subtitle" do %>
                    { <%= sponsor.name %> }
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </aside>

    <section id="content-section">
      <div id="headline">
        <%= image_tag 'pencil.png' %>
        <h2>Upcoming Events</h2>
      </div>

      <div class="classes">
      </div>

      <% if @leaders.count != 0 %>
        <div id="headline">
          <%= image_tag 'flourish.png' %>
          <h2>Chapter Leaders</h2>
        </div>
      <% end %>

      <div class="profiles">

        <% @leaders.each do |bio| %>
          <div class="single-profile">
            <div class="profile-img">
              <% if bio.image? %>
                <%= image_tag bio.image %>
              <% elsif bio.pic_link? %>
                <%= image_tag bio.pic_link %>
              <% else %>
                <%= image_tag "photo-not-available.jpg" %>
              <% end %>
            </div>

            <div class="profile-content">
              <h3><%= bio.name %></h3>
              <% if bio.info[0, 3] == "<p>" %>
                <%= bio.info.html_safe %>
              <% else %>
                <%= auto_link(simple_format(bio.info.html_safe)) %>
              <% end %>
              <%= render partial: "social_media_bio", locals: {bio: bio} %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="profiles">
        <% if @instructors.count != 0 %>
          <div id="headline">
            <%= image_tag 'apple.png' %>
            <h2>The Instructors</h2>
          </div>
        <% end %>

        <% @instructors.each do |bio| %>
          <div class="single-profile">
            <div class="profile-img">
              <% if bio.image? %>
                <%= image_tag bio.image %>
              <% elsif bio.pic_link? %>
                <%= image_tag bio.pic_link %>
              <% else %>
                <%= image_tag "photo-not-available.jpg" %>
              <% end %>
            </div>

            <div class="profile-content">
              <h3><%= bio.name %></h3>
              <% if bio.info[0, 3] == "<p>" %>
                <%= bio.info.html_safe %>
              <% else %>
                <%= simple_format(bio.info.html_safe) %>
              <% end %>
              <%= render partial: "social_media_bio", locals: {bio: bio} %>

            </div>
          </div>
        <% end %>
      </div>

      <div class="profiles">
        <% if @volunteers.count != 0 %>
          <div id="headline">
            <%= image_tag 'apple.png' %>
            <h2>The Volunteers</h2>
          </div>
        <% end %>

        <% @volunteers.each do |bio| %>
          <div class="single-profile">
            <div class="profile-img">
              <% if bio.image? %>
                <%= image_tag bio.image %>
              <% elsif bio.pic_link? %>
                <%= image_tag bio.pic_link %>
              <% else %>
                <%= image_tag "photo-not-available.jpg" %>
              <% end %>
            </div>

            <div class="profile-content">
              <h3><%= bio.name %></h3>
              <% if bio.info[0, 3] == "<p>" %>
                <%= bio.info.html_safe %>
              <% else %>
                <%= simple_format(bio.info.html_safe) %>
              <% end %>
              <%= render partial: "social_media_bio", locals: {bio: bio} %>

            </div>
          </div>
        <% end %>
      </div>

      <script type="text/template" id="meetup">
      <%% _.each( classesArr,function(course){ %>
        <h3><a href="<%%= course.event_url %>"><%%= course.name %></a></h3>
        <p class="subtitle">[ <%%= moment(course.time).format("dddd, MMMM Do YYYY, h:mm a") %>
        <%% if(typeof course.venue !== "undefined" && course.visibility === "public") { %>
            , <a href=" https://maps.google.com/?q=<%%= course.venue.address_1 %>, <%%= course.venue.city %>, <%%= course.venue.state %>"><%%= course.venue.address_1 %>,<%%= course.venue.city %>,<%%= course.venue.state %></a>
          <%% } %>
          ] </p>
          <%= render partial: "meetup_map"%>
         <p><%%= course.description.substring(0, 400) %><a href="<%%= course.event_url %>">...read more</a></p>
         <a href="<%%= course.event_url %>" class="button">RSVP</a>
       <%% }); %>
      </script>

      <script type="text/javascript">

        var meetup_url = '/meetups/<%= params[:id] %>.json';
        var classesArr = null;
        $.getJSON(meetup_url).done(function (classesData){
          if(classesData.length>0) {
            classesArr = classesData.slice(0,3);
            var classes = $('#meetup').html();
            //instead send classesArr to template where _.each is waiting...
            //idea seen here: http://stackoverflow.com/questions/4778881/how-to-use-underscore-js-as-a-template-engine
            $(".classes").html(_.template(classes,classesArr));
          } else {
            $(".classes").html("<p class=\"uhOh\">Sadly, no meetups are currently scheduled for this Chapter. <a href=\"http://meetup.com/<%= @chapter.meetup %>\">Join our meetup group</a> to be notified when a new meetup is happening. Thanks for visiting us!</p>")};
          });

      </script>
    </section>
  </div>
</section>

app/views/home/code-of-conduct.html.erb
<% provide(:title, "Code of Conduct") %>
<section class="main-container">


  <div class="container">

    <section class="code">
        <div class="underlined-headline">
          <h2>Code of Conduct</h2>
          <hr>
        </div>
        <h3>Purpose</h3>
        <p>Girl Develop It is dedicated to providing a harassment-free community and learning experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, or religion. We expect all attendees to show respect and courtesy to other attendees throughout Girl Develop It classes and events. Sexual language and imagery is not appropriate for any Girl Develop It event. Girl Develop It participants violating these rules may be sanctioned or expelled from our events or online discussion boards without a refund at the discretion of the event organizers.</p><br>
        <h3>Harassment</h3>
        <p>Harassment includes offensive verbal comments related to gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, or religion; sexual images in public spaces; deliberate intimidation; stalking; following; harassing photography or recording; sustained disruption of talks or other events; inappropriate physical contact; and unwelcome sexual attention. Adults who identify as men are welcome at our events, and it is expected that all participants be treated with equal respect. We do not tolerate harassment of Girl Develop It participants in any form. All communication should be appropriate for a professional audience. Participants asked to stop any harassing behavior are expected to comply immediately.</p><br>
        <h3>Privacy Concerns</h3>
        <p>Your privacy is important to us. While photographs may be taken in class and can be shared by group members in the group’s meetup page, no photograph shall be used for promotional purposes without verbal and/or written consent of the attendees. If a group photograph is taken, your participation will serve as your agreement to the use of such a photograph for Girl Develop It promotional purposes. If you are uncomfortable having your photograph shared, please let us know.</p><br>
        <h3>Use of Sexualized Imagery</h3>
        <p>Teachers, event organizers, volunteers, and hosts are also subject to the anti-harassment policy. In particular, teachers/hosts/organizers should not use sexualized images, activities, or other material. GDI organizers, teachers, teachers assistants, and event hosts (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment.</p><br>
        <h3>Consequences Of Unacceptable Behavior</h3>
        <p>If a participant engages in harassing behavior, the Girl Develop It organizers may take any action they deem appropriate, including warning the offender or expelling him or her from the class/event/meetup group [with no refund]. </p><br>
        <h3>What To Do If You Witness Or Are Subject To Unacceptable Behavior</h3>
        <p>If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact your local Chapter Leader(s) immediately. Contact information for your local Chapter Leader can be found on <%= link_to "our Chapters page", chapters_path %>.</p>
        <p>Girl Develop It Chapter Leaders/Teachers/Event Organizers will be happy to help members contact local law enforcement, provide escorts when possible and with reasonable notice, or otherwise assist those experiencing harassment to feel safe for the duration of the event/class. We value your attendance.</p>
        <p>Girl Develop It expects participants to follow these rules at all Girl Develop It social events and in online discourse.</p><br>
        <h3>Contact Information</h3>
        <p>If you have any questions, please contact your local chapter. Contact information for your local Chapter Leader can be found on <%= link_to "our Chapters page", chapters_path %>.</p>
    </section>





  </div>
</section>

app/views/home/index.html.erb
  <div class="opener">
    <%#= image_tag("photo2.png") %>
    <h1><span class="animated fadeInLeft">Don't be shy</span> <%= image_tag("flourish-med.png" , class: "hide") %> <span class="animated fadeInRight">Develop it</span></h1>
  </div>

  <div class="container" >
  	<section class="mission-statement">
      <div class="underlined-headline">
        <h2>Who are we?</h2>
        <hr>
      </div>
    	<p class="large">Girl Develop It is a nonprofit organization that exists to provide affordable and accessible programs for women interested in learning web and software development. Through mentorship and hands-on instruction Girl Develop It helps women of diverse backgrounds reach their goals. Our vision is to create a network of empowered women who are confident in their abilities to code and build beautiful web applications. Through teaching women around the world to learn software development, we can help them improve their careers and the confidence they carry with them in their everyday lives.</p>
      <%= link_to "[ Learn more ]", about_path, :class=>"subtitle"%>
    </section>
  </div>

  <section class="map">
    <div class="container">
    	<div class="underlined-headline">
        <h2>We are now in <%= @chapters.count %> cities!</h2>
        <hr>
        <p class="subtitle hide">
          Don't see your hometown?
          <% if current_admin_user != nil %>
            <%= link_to "Start a new chapter!", "#{root_path}admin/chapters/new" %>
            <% else %>
            <a href="https://docs.google.com/a/girldevelopit.com/forms/d/1IwGncJ6_69MWa2_rrikO5Q3DLriA04Eq9x0BUnxkwTw/viewform?edit_requested=true#start=invite">Start a new chapter!</a>
          <% end %>
        </p>
        <%=link_to "Find GDI in your hometown!", chapters_path, :class=>" subtitle show-inline"%>
      </div>
      <div class="us_map hide">
        <div class="map"></div>
      </div>
    </div>
  </section>

  <section class="stats-section">
    <div class="container">
      <div class="stats">
        <%= image_tag("homepage-stat1.png", :alt => "26 percent") %>
        <p>Women hold only 26% of the approximately four million computing related occupations in the US. <%= link_to "U.S. Department of Labor, Bureau of Labor Statistics, 2013 (Occupational Category: 15–0000)", "http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf", target: "_blank" %></p>
      </div>
      <div class="stats">
        <%= image_tag("homepage-stat2.png", :alt => "18 percent") %>
        <p>Women obtain 57% of bachelor’s degrees in the U.S, but fewer than 18% of those degrees are in computer science. (Compared to 1984, when women earned 37%) <%= link_to "National Center for Education Statistics (NCES), 2012 (CIP 11)", "http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf", target: "_blank" %></p>
      </div>
      <div class="stats">
        <%= image_tag("homepage-stat3.png", :alt => "34 percent") %>
        <p>Tech companies with more women in management have a 34% higher return of investment. <%= link_to "National Center for Women and IT Fact Sheet", "http://www.ncwit.org/sites/default/files/resources/ncwitfactsheet.pdf", target: "_blank" %></p>
      </div>
    </div>
  </section>

  <div class="press-logos">
    <h3>{ As seen in }</h3>
    <%#= image_tag("press-logos.png") %>
    <%= link_to image_tag("as_seen_in/code_org.png"), "https://www.youtube.com/watch?v=nKIu9yen5nc", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/tnyt.png"), "http://www.nytimes.com/2012/03/28/technology/for-an-edge-on-the-internet-computer-code-gains-a-following.html", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/ted.png"), "http://blog.ted.com/2013/01/29/10-places-where-anyone-can-learn-to-code/", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/fast_company.png"), "http://www.fastcompany.com/1776382/female-geeks-flex-their-skills-ladies-only-hackathon", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/lifehacker.png"), "http://lifehacker.com/5872682/learn-to-code-in-2012-with-free-weekly-programming-lessons-from-codecademy", target: "_blank" %>
  </div>
  <script>
    var chapter_id = "chapters/3";
  </script>

app/views/materials/index.html.erb
<% provide(:title, "Materials") %>
  <section class="main-container">
  <div class="container">

    <div class="underlined-headline">
      <h2>Materials</h2>
      <hr>
      <p class="large">Girl Develop It materials are built by our community, which is made up of industry-leading technologists, instructors, and leaders. All curriculum developed by GDI can be licensed under fair use <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="blank">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)</a>. You are free to share and adapt these materials.</p>
    </div>

    <section class="material-index hide">
      <% @materials.each do |s| %>
        <div class="material-container">
          <div class="material-icon">
            <% if s.icon? %>
              <%= link_to(image_tag(s.icon,:height => 80), course_url(slug: s.slug)) %>
            <% else %>
              <%= link_to(image_tag("materials/materials-icon-not-available.png", :height=>80), course_url(slug: s.slug)) %>
            <% end %>
          </div>
          <div class="material-title">
          <h2><%= link_to s.title, course_url(slug: s.slug) %></h2>
              <p><%= s.short_description %></p>
          </div>
        </div>
    <% end %>
    </section>

    <section id="materials-list">
      <div class="accordion show">
        <% @materials.each do |s| %>
          <section class="hidden">
             <h2><%= link_to s.title, course_url(slug: s.slug) %></h2>
          </section>
        <% end %>
      </div>
    </section>
  </div>
  </section>

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
		<div class="footer">
			<p class="subtitle hide">Don't see your city? <a target="_blank" href="https://docs.google.com/a/girldevelopit.com/forms/d/1IwGncJ6_69MWa2_rrikO5Q3DLriA04Eq9x0BUnxkwTw/viewform?edit_requested=true#start=invite">Help bring Girl Develop It to your home town.</a></p>
			<p class="subtitle">To become a sponsor or for partnership opportunities, email  us at <%= mail_to "sponsorships@girldevelopit.com" %> </p>
			<!-- Begin MailChimp Signup Form -->
			
			
			<div id="mc_embed_signup">
			<form action="//girldevelopit.us2.list-manage.com/subscribe/post?u=4d5ae11ec6fb973947670055f&amp;id=e63c9ab02b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
			    <div id="mc_embed_signup_scroll">
				<!-- <label for="mce-EMAIL">Subscribe to our mailing list</label><br> -->
				<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" size="40" placeholder="email address" required>
			    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
			    <div style="position: absolute; left: -5000px;"><input type="text" name="b_4d5ae11ec6fb973947670055f_e63c9ab02b" tabindex="-1" value=""></div>
			    <div class="clear"><input type="submit" value="Subscribe to Mailing List" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
			    </div>
			</form>
			</div>

			<!--End mc_embed_signup-->
			<nav class="navigation">
				<%= link_to "about", about_path %>
				<%= link_to "code of conduct", code_of_conduct_path %>
				<%= link_to "sponsors", sponsors_path %>
				<%#= link_to "partners", root_path, class: "hide" %>
				<a target="_blank" href="http://girldevelopit.tumblr.com/">blog</a>
				<% if current_admin_user != nil %>
					<%= link_to "admin", admin_root_path %>
					<%= link_to "logout", destroy_admin_user_session_path %>
				<% end %>
			</nav>
			<nav class="navigation">
				<a target="_blank" href="https://twitter.com/girldevelopit"><i class="fa fa-twitter"></i></a>
			  <a target="_blank" href="https://www.facebook.com/girldevelopit"><i class="fa fa-facebook"></i></a>
			</nav>
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <%= link_to image_tag("gdi-logo.png"), root_path, class:"logo" %>
    <nav class="navigation">
      <ul>
        <li><%= link_to "donate", donate_path, class:active_page(donate_path) %></li>
        <li><%= link_to "about", about_path, class:active_page(about_path) %></li>
        <li><%= link_to "chapters", chapters_path, class:active_page(chapters_path) %></li>
        <li><%= link_to "materials", materials_path, class:active_page(materials_path)%></li>
        <li><%= link_to "sponsors", sponsors_path, class:active_page(sponsors_path) %></li>
      </ul>
      <ul>
        <li>
          <a target="_blank" href="https://twitter.com/girldevelopit">
            <i class="fa fa-twitter"></i>
          </a>
        </li>
        <li>
          <a target="_blank" href="https://www.facebook.com/girldevelopit">
            <i class="fa fa-facebook"></i>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</header>